# frozen_string_literal: true

source "https://rubygems.org"

gem "rubocop-rspec", "~> 2.22", require: false
gem "rubocop-performance", "~> 1.16", require: false
gem "standard", "~> 1.28", require: false

group :test do
  gem "rspec", "~> 3.13"
  gem "rspec-example_steps", "~> 3.1"
end
