name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  simple-telemetry-build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3.1'

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Run the default task
      working-directory: ./simple-telemetry
      run: bundle && bundle exec rake

  e2e-tests:
    name: E2E
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: build
        working-directory: ./e2e-tests
        run: |
          bundle
          echo "not running till work out how to time out a failed run"
          # bundle exec rspec
