name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  simple-telemetry-build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2.0'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      working-directory: ./simple-telemetry
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      working-directory: ./simple-telemetry
      run: bundle exec rake
